### ISSUE TITLE
IsPlaying Doesn't Exist >:(

### ISSUE THREAD

**Issue by MunaAlaneme** [vrld/slam#5]
Error:

main.lua:133: attempt to call method 'isPlaying' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
main.lua:133: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by vrld** [comment]
solved by #6
